global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
 - job_name: 'metrics'
   scheme: http
   metrics_path: '/plugins/metrics-reporter-prometheus/metrics'
   params:
      format: ['prometheus']
   bearer_token: token
   scrape_interval: 5s
   static_configs:
      - targets: ['$DOCKERHOST:18080','$DOCKERHOST:18081']
        labels:
          env: 'unit'
