version: '3'
services:
  tester:
    image: gerritcodereview/gerrit:${GERRIT_IMAGE}
    user: root
    depends_on:
      gerrit1:
        condition: service_healthy
      gerrit2:
        condition: service_healthy
    entrypoint: ["/var/gerrit/scenarios.sh"]
