version: '3'
services:
  kafka:
    image: wurstmeister/kafka:2.12-2.1.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    container_name: kafka_test_node
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  gerrit1:
    depends_on:
      - kafka

  gerrit2:
    depends_on:
      - kafka