version: '3'
services:
  kafka:
    image: bitnami/kafka:3.6.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  gerrit1:
    depends_on:
      - kafka

  gerrit2:
    depends_on:
      - kafka