version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest

  gerrit1:
    image: gerritcodereview/gerrit:${GERRIT_IMAGE}
    depends_on:
      - zookeeper
    volumes:
      - "gerrit1_git:/var/gerrit/git"
      - "gerrit2_git:/var/gerrit/git-instance2"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/config/server/healthcheck~status"]
      start_period: ${GERRIT_HEALTHCHECK_START_PERIOD:-60s}
      interval: ${GERRIT_HEALTHCHECK_INTERVAL-5s}
      timeout: ${GERRIT_HEALTHCHECK_TIMEOUT-5s}
      retries: ${GERRIT_HEALTHCHECK_RETRIES-5}

  gerrit2:
    image: gerritcodereview/gerrit:${GERRIT_IMAGE}
    depends_on:
      - zookeeper
    volumes:
      - "gerrit2_git:/var/gerrit/git"
      - "gerrit1_git:/var/gerrit/git-instance1"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/config/server/healthcheck~status"]
      start_period: ${GERRIT_HEALTHCHECK_START_PERIOD:-60s}
      interval: ${GERRIT_HEALTHCHECK_INTERVAL:-5s}
      timeout: ${GERRIT_HEALTHCHECK_TIMEOUT:-5s}
      retries: ${GERRIT_HEALTHCHECK_RETRIES:-5}

volumes:
  gerrit1_git:
  gerrit2_git: