version: '3'
services:
  zookeeper:
    image: zookeeper:3.5.7
    ports:
      - "2181:2181"
    container_name: zk_test_node
    environment:
      ZK_CLIENT_PORT: 2181
      ZK_SECURE_CLIENT_PORT: 2281
      ZK_REPLICAS: 1
  prometheus:
    container_name: prometheus_test_node
    image: prom/prometheus:v2.16.0
    user: root
    volumes:
     - $COMMON_LOCATION/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    network_mode: $NETWORK_MODE
