version: '3'
services:
  pubsub:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:316.0.0-emulators
    ports:
      - "8085:8085"
    container_name: gcloud-pubsub_test_node
    entrypoint: gcloud beta emulators pubsub start --project test-project --host-port 0.0.0.0:8085
    networks:
      - setup_local_env_default
networks:
  setup_local_env_default:
    external: true
