version: '3'
services:
  kafka:
    image: bitnami/kafka:3.6.0
    ports:
      - "9092:9092"
    container_name: kafka_test_node
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - setup_local_env_default
networks:
  setup_local_env_default:
    external: true
