version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    container_name: zk_test_node
  prometheus:
    container_name: prometheus_test_node
    image: prom/prometheus:v2.16.0
    user: root
    volumes:
     - $COMMON_LOCATION/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    network_mode: $NETWORK_MODE
