version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    container_name: zk_test_node
  kafka:
    image: wurstmeister/kafka:2.12-2.1.0
    ports:
      - "9092:9092"
    container_name: kafka_test_node
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "gerrit_index:1:1,gerrit_stream:1:1,gerrit_list_project:1:1,gerrit_cache_eviction:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
