version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper:3.8.3
    ports:
      - "2181:2181"
    container_name: zk_test_node
    environment:
        ZOO_ENABLE_AUTH: "true"
        ZOO_SERVER_USERS: "globalrefdb"
        ZOO_CLIENT_USER: "globalrefdb"
        ZOO_CLIENT_PASSWORD: "globalrefdb-secret"
        ZOO_SERVER_PASSWORDS: "globalrefdb-secret"
        ALLOW_ANONYMOUS_LOGIN: "true"
  prometheus:
    container_name: prometheus_test_node
    image: prom/prometheus:v2.16.0
    user: root
    volumes:
     - $COMMON_LOCATION/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    network_mode: $NETWORK_MODE
