version: '3'
services:
  kafka:
    image: wurstmeister/kafka:2.13-2.6.3
    ports:
      - "9092:9092"
    container_name: kafka_test_node
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - setup_local_env_default

  kafka-rest-1:
    image: confluentinc/cp-kafka-rest:6.0.5
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_ID: kafka_rest_1
      KAFKA_REST_HOST_NAME: 127.0.0.1
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_REST_LISTENER: http://127.0.0.1:8082

  kafka-rest-2:
    image: confluentinc/cp-kafka-rest:6.0.5
    ports:
      - "8083:8082"
    environment:
      KAFKA_REST_ID: kafka_rest_2
      KAFKA_REST_HOST_NAME: 127.0.0.1
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_REST_LISTENER: http://127.0.0.1:8082

  haproxy-kafka:
    image: haproxy:latest
    ports:
      - "8085:8080"
    volumes:
     - "./haproxy-config-kafka:/usr/local/etc/haproxy"

networks:
  setup_local_env_default:
    external: true
